= Linux


quick and dirty sshfs::
    . install `sshfs`
    . `mount -t fuse.sshfs user@ip:/path /mount/point`

NTP sync::
    `systemd ? timedatectl : ntpd`


== Centos

WARNING: If after long time of not using centos, `yum update` fails, use `yum clean all`

== systemd

* if the **service** has autorecovery code, for example, you connecto to a JMS
server and you reconnect when connection drops. **USE `Wants` INSTEAD OF
`Requires`**

* If you want to start services in some order, use `After=` or `Before=`

Disable stdout -> journal:: `StandardOutput=null` 

== Development

See needed libraries and rpath data::
    readelf -d <filename>

WARNING: if `ld.so.conf` is modified, you need to run `ldconfig`.

=== RPATH

escape `$ORIGIN` in one `Makefile` calling another `Makefile`::
    `-Wl,-rpath,'+++\$$\$$$$ORIGIN/../lib+++'`

NOTE: if using `rpath` and want to be able to copy indirect `.so` libraries to the relative `rpath` you also need to link them in: `g++ other/files -L ... -lotherlibs -L indirect/libraries/path -lindirectlib`

